### ISSUE TITLE
Changer la config DNS pour permettre le https

### ISSUE THREAD

**Issue by fredZen** [agileopenfrance/agileopenfrance.com#2]
# Symptôme

La recherche google sur _agile open france_ me remonte actuellement une page en https.

![résultat de recherche google pour agile open france : la page remontée a un lien en https](https://user-images.githubusercontent.com/356570/49106811-73f76c80-f284-11e8-9ba4-153cef4ec687.png)

Quand je suis le lien https://agileopenfrance.com, j’obtiens une alerte de sécurité

![alerte de sécurité : la page consultée est sur agileopenfrance.com mais le certificat est pour *.github.com](https://user-images.githubusercontent.com/356570/49106950-c6388d80-f284-11e8-8f59-de67e001d9aa.png)

# Explication

Depuis mai 2018, GitHub [gère les github-pages en https](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/), même sur un domaine custom. Manifestement, google a « vu » que l’adresse https était disponible.

Malheureusement, les adresses IP historiques des github-pages n’ont qu’un certificat en github.com, d’où l’alerte de sécurité.

# Solution

Mettre [les nouvelles adresse IP](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider) dans les enregistrements A pour agileopenfrance.com sur gandi.

**Comment by ronnix** [comment]
J’ai l’impression que le site fonctionne bien en HTTPS maintenant, et que le nom de domaine pointe sur les bonnes adresses IP.

```
$ host -t A agileopenfrance.com
agileopenfrance.com has address 185.199.110.153
agileopenfrance.com has address 185.199.109.153
```
